In [2]:
import pandas as pd
import numpy as np

In [18]:
num1 = np.array([[1,2,3],[2,4,6],[3,4,5]])
num2 = np.array([[3,4,5],[4,6,8],[5,6,7]])

In [19]:
print(num1)
print(num2)

[[1 2 3]
 [2 4 6]
 [3 4 5]]
[[3 4 5]
 [4 6 8]
 [5 6 7]]


## mean() 求均值

In [20]:
np.mean(num1)

3.3333333333333335

In [21]:
np.mean(num2)

5.333333333333333

**压缩行，对各列求均值

In [22]:
h1 = np.mean(num1, 0)
h2 = np.mean(num2, 0)
print(h1, h2)

[2.         3.33333333 4.66666667] [4.         5.33333333 6.66666667]


**压缩列，对各行求均值

In [23]:
l1 = np.mean(num1, 1)
l2 = np.mean(num2, 1)
print(l1, l2)

[2. 4. 4.] [4. 6. 6.]
