In [2]:
import pandas as pd
import numpy as np

In [18]:
num1 = np.array([[1,2,3],[2,4,6],[3,4,5]])
num2 = np.array([[3,4,5],[4,6,8],[5,6,7]])

In [19]:
print(num1)
print(num2)

[[1 2 3]
 [2 4 6]
 [3 4 5]]
[[3 4 5]
 [4 6 8]
 [5 6 7]]


## mean() 求均值

In [20]:
np.mean(num1)

3.3333333333333335

In [21]:
np.mean(num2)

5.333333333333333

**压缩行，对各列求均值**

In [22]:
h1 = np.mean(num1, 0)
h2 = np.mean(num2, 0)
print(h1, h2)

[2.         3.33333333 4.66666667] [4.         5.33333333 6.66666667]


**压缩列，对各行求均值**

In [23]:
l1 = np.mean(num1, 1)
l2 = np.mean(num2, 1)
print(l1, l2)

[2. 4. 4.] [4. 6. 6.]


## dataframe.std()

**函数返回请求轴上的样品标准偏差。**

用法：DataFrame.std(axis=None, skipna=None, level=None, ddof=1, numeric_only=None, **kwargs)

参数：

axis:{索引(0)，列(1)}

skipna:排除NA /空值。如果整个行/列均为NA，则结果为NA

level:如果轴是MultiIndex(分层)，则沿特定级别计数，并折叠为Series

ddof:Delta自由度。计算中使用的除数为N-ddof，其中N表示元素数。

numeric_only:仅包括float，int，boolean列。如果为None，将尝试使用所有内容，然后仅使用数字数据。未针对系列实施。

In [25]:
num1.std(axis=0)

array([0.81649658, 0.94280904, 1.24721913])

## to_list()函数
pandas.Series转换成list

In [4]:
s = pd.Series(data=np.arange(7), dtype=np.float32, index=list('abcdefg'))
s
l = []
l = s.to_list()
print(l)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
